import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const T=process.env.T;
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox','--disable-gpu']});
const p=await b.newPage({viewport:{width:412,height:915},deviceScaleFactor:1});
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERR '+e.message));
await p.goto('http://localhost:5173/onboarding',{waitUntil:'networkidle'});
await p.waitForTimeout(2000);
await p.screenshot({path:T+'/welcome-new.png', fullPage:true});
console.log('ERRORS:',errs.slice(0,6));
await b.close();
